In [106]:
# identifying missing values using isnull() or isna():

import pandas as pd

# creating a sample dataframe
data = {
    'Num':[1,2,None,4,5],
    'alph':['A','B',None,'D','E'],
    'alpha':['x','y','z',None,'w']
}
df= pd.DataFrame(data)
df

# checking for missing values:
missing_values= df.isnull()
print(missing_values)

# counting missing values in each column:
missing_values_count= df.isnull().sum()
print(missing_values_count)

# checking if any missing values exist in the dataframe:
check_missing_values= df.isnull().values.any()
check_missing_values

     Num   alph  alpha
0  False  False  False
1  False  False  False
2   True   True  False
3  False  False   True
4  False  False  False
Num      1
alph     1
alpha    1
dtype: int64

np.True_

In [107]:
# removing rows or columns with missing values using dropna():

# dropping rows with any missing values:
df_without_missing= df.dropna()
print(df_without_missing)

# dropping columns with any missing values:
df_without_missingc=df.dropna(axis=1)
print(df_without_missingc)

# dropping rows with missing values in specfic columns:
df_without_missingsc= df.dropna(subset=['Num','alph'])
df_without_missingsc

   Num alph alpha
0  1.0    A     x
1  2.0    B     y
4  5.0    E     w
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

   Num alph alpha
0  1.0    A     x
1  2.0    B     y
3  4.0    D   NaN
4  5.0    E     w

In [108]:
# filling missing values using fillna() with methods like mean, median, and forward/backward filling:

# filling missing values with mean of each column:
df1= df.fillna(df.mean)
df1
# filling missing values with median of each column:
df1= df.fillna(df.median)
df1
# filling missing values using forward filling(propagating last valid observation forward)
df3= df.ffill()
df3
# filling missing values using backward filling(propagating next valid observation forward)
df3= df.bfill()
df3

   Num alph alpha
0  1.0    A     x
1  2.0    B     y
2  4.0    D     z
3  4.0    D     w
4  5.0    E     w

In [109]:
# standardizing data  formats using pandas' string manipulation functions (str.lower(),str.upper(),str.replace()):

# creating a sample dataframe
data= {'column_name':['value1','value2','old_string','value4']}
df1= pd.DataFrame(data)
df1

# converting column values to lowercase:
df1['column_name']= df1['column_name'].str.lower()
df1['column_name']

# converting column values to uppercase:
# df1['column_name']= df1['column_name'].str.upper()
# df1['column_name']

# replacing a specific substring in column values:
df1['column_name']= df1['column_name'].str.replace('old_string','new_string')
df1['column_name']

0        value1
1        value2
2    new_string
3        value4
Name: column_name, dtype: str

In [110]:
# correcting inconsistent data using replace() function:

df=df1.copy()
# assuring 'df' is your dataframe and 'column_name' is the name of the column you want to correct:
# replacing  specific values with new values:
df['column_name']= df['column_name'].replace({'value1':'A','value2':'B'})
df['column_name']
# replacing values based on a condition:
df['column_name']=df['column_name'].replace('new_string','C', regex=True)
df
# replacing values using regular expressions (re module): 
import re
df['column_name']=df['column_name'].apply(lambda x: re.sub(r'pattern', 'replacement', x))
df['column_name']

0         A
1         B
2         C
3    value4
Name: column_name, dtype: str

In [111]:
# converting data types using astype():
data={
    'nume': [1,2,3,4,5],
    'flo': [1.2,2,5,7,4.5],
    'stri': ['anna','bob','magnus','firouja','messi']
}
df=pd.DataFrame(data)
df
# converting column to integer type:
df['nume']=df['nume'].astype(int)
df['nume']
# converting column to float type:
df['flo']=df['flo'].astype(float)
df['flo']
# converting column to string type:
df['stri']=df['stri'].astype(str)
df['stri']
# converting column to datetime type:
df['nume']=pd.to_datetime(df['nume'])
df['nume']

0   1970-01-01 00:00:00.000000001
1   1970-01-01 00:00:00.000000002
2   1970-01-01 00:00:00.000000003
3   1970-01-01 00:00:00.000000004
4   1970-01-01 00:00:00.000000005
Name: nume, dtype: datetime64[ns]

In [112]:
# converting data types using to_numeric():

# creating a sample dataframe:
data = {
    'nums' : ['1','2','3','4','5','apple']
}
df=pd.DataFrame(data)
df

# converting column to numeric type:
# df['nums']= pd.to_numeric(df['nums'])
# df['nums']

# converting column to numeric type with handling of errors:
df['nums']= pd.to_numeric(df['nums'], errors= 'coerce')
df['nums']

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
Name: nums, dtype: float64

In [113]:
# detecting outliers using z-score and iqr

import pandas as pd
import numpy as np

# creating a sample dataframe:
data={'nu':[10,15,12,8,20,25,7,300000]}
df=pd.DataFrame(data)
df
# calculating z-score for the column:
z_scores = (df['nu']-df['nu'].mean())/df['nu'].std()

# defining a threshold for outlier detection(e.g, z-score>3 or < -3):
threshold = 3
# identifying outliers based on the threshold:
outliers= df[abs(z_scores)>threshold]
# checking if outliers dataframe is empty:
if outliers.empty:
    print('No outliers')
else:
    print('outliers')

No outliers

In [114]:
import pandas as pd
import numpy as np

# creating a sample dataframe:
data={'na':[10,15,12,8,20,25,7,300000]}
df=pd.DataFrame(data)
df
# calculating the first quartile(Q1):
q1= df['na'].quantile(0.25)
q1
# calculating the third  quartile(Q3):
q3= df['na'].quantile(0.75)
q3
# calculating the IQR:
IQR= q3-q1
IQR
# defining a threshold for outlier detection(e.g, values outside the range[ q1-1.5*IQR, q3+1.5*IQR] are considered):
lower_threshold= q1-1.5*IQR
lower_threshold
upper_threshold= q3+1.5*IQR
upper_threshold
# identifying outliers based on the threshold:
outliers= df[(df['na']<lower_threshold) | (df['na']>upper_threshold)]
outliers
# checking if outliers dataframe is empty:
if outliers.empty:
    print('No outliers')
else:
    print('outliers')

outliers

In [115]:
import pandas as pd

# creating sample dataframes
df1=pd.DataFrame({'id':[1,2,3,4],
                  'name':['john','alice','bob','emily']})
df2=pd.DataFrame({'id':[2,3,5,6],
                  'city':['new york','london','paris','berlin']})

# inner join: returns the intersection of the two datasets based on a common key:
inner_join= pd.merge(df1,df2,on='id',how='inner')
inner_join

# left join: returns all records from the left dataset and matching records from the right dataset:
left_join= pd.merge(df1,df2,on='id',how='left')
left_join

# right join: returns all records from the right dataset and matching records from the left dataset:
right_join= pd.merge(df1,df2,on='id',how='right')
right_join

# outer join: returns all records when there is a match in either the left or right dataset:
full_join= pd.merge(df1,df2,on='id',how='outer')
full_join

   id   name      city
0   1   john       NaN
1   2  alice  new york
2   3    bob    london
3   4  emily       NaN
4   5    NaN     paris
5   6    NaN    berlin